### PR TITLE
Fix application icon on Wayland

### PR DESCRIPTION
**Pull request by RevengeRip**
In order for the application to have a proper icon on Wayland in various places (window decoration, task switcher) it should have a proper desktop entry file that follows [XDG Desktop Entry Naming convention](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html) and proper icons set. I took a liberty to give it an "org.cachyos.KernelManager" application ID.
| Before | After |
|--------|--------|
| Снимок экрана_20241201_001639| Снимок экрана_20241201_001122|
| Снимок экрана_20241201_001727 | Снимок экрана_20241201_001811 |

### CODE REVIEW

**Comment by vnepogodin** [comment]
Well just the image filename must match the class name that it reports for self

**Comment by RevengeRip** [comment]
It's rather difficult on Wayland: an application must set a proper appid/desktopfilename that follows xdg desktop entry spec, and then have a corresponding desktop entry that points to the icon name.

**Comment by vnepogodin** [comment]
> It's rather difficult on Wayland: an application must set a proper appid/desktopfilename that follows xdg desktop entry spec, and then have a corresponding desktop entry that points to the icon name.

fair

**Review by vnepogodin — CHANGES_REQUESTED** [review]
rename previous desktop name everywhere from `org.cachyos.cachyos-kernel-manager` to `org.cachyos.KernelManager`

including the filename of polkit policy `org.cachyos.cachyos-kernel-manager.pkexec.policy` and the string in the polkit policy file `<action id="org.cachyos.cachyos-kernel-manager.pkexec.policy.run-root-terminal">`

**Comment by RevengeRip** [comment]
Done

**Review by vnepogodin — APPROVED** [review]
Many thanks!

**Pull request merged**
